{%- from "metalk8s/repo/macro.sls" import build_image_name with context -%}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: ui
    kubernetes.io/name: "MetalK8sUI"
spec:
  selector:
    matchLabels:
      k8s-app: ui
  template:
    metadata:
      labels:
        k8s-app: ui
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/bootstrap"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/infra"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/infra: ''
      containers:
        - name: metalk8s-ui
          image: {{ build_image_name('metalk8s-ui') }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          volumeMounts:
          - name: metalk8s-ui-volume
            mountPath: /etc/metalk8s/ui
            readOnly: true
      volumes:
        - name: metalk8s-ui-volume
          configMap:
            name: metalk8s-ui
