apiVersion: v1
kind: Pod
metadata:
  name: "terraform-worker-multiple-nodes"
spec:
  containers:
  - name: terraform-worker
    image: {{ images['docker-terraform'] }}
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    command: ["/bin/sh"]
    args: ["-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
