---
version: "0.2"

branches:
  user/*:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: local
    steps:
      - SetPropertyFromCommand:
          name: Test "on"
          property: run_next_step
          command: >
              echo "on"
      - ShellCommand: &ok
          name: That should work
          command: exit 0
          doStepIf: "%(prop:run_next_step)s"
      - SetPropertyFromCommand:
          name: Test "true"
          property: run_next_step
          command: >
              echo "true"
      - ShellCommand: *ok
      - SetPropertyFromCommand:
          name: Test "1"
          property: run_next_step
          command: >
              echo "1"
      - ShellCommand: *ok
      - SetPropertyFromCommand:
          name: Test "off"
          property: run_next_step
          command: >
              echo "off"
      - ShellCommand: &nok
          name: That should not work
          command: exit 1
          doStepIf: "%(prop:run_next_step)s"
      - SetPropertyFromCommand:
          name: Test "false"
          property: run_next_step
          command: >
              echo "false"
      - ShellCommand: *nok
      - SetPropertyFromCommand:
          name: Test "0"
          property: run_next_step
          command: >
              echo "0"
      - ShellCommand: *nok
